services:
  discord-bot:
    image: node:20-bullseye-slim
    container_name: coc-discord-bot
    volumes:
      - .:/coc_discord_bot
    working_dir: /coc_discord_bot
    command: bash -c "npm install && npm run start"
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env

secrets:
  COC_API_KEY:
    external: true
  DISCORD_KEY:
    external: true
